---
# tasks file for atomic_red_team

- name: Setup Windows
  ansible.builtin.include_tasks: "setup-windows.yml"
  when: ansible_system == 'Win32NT'

- name: Setup Linux
  ansible.builtin.include_tasks: "setup-linux.yml"
  when: ansible_system == 'Linux'

- name: Run invoke-atomictest on each TID (linux)
  ansible.builtin.include_tasks: invoke-atomictest.yml
  loop: "{{ atomic_red_team_art_tids_linux | difference(atomic_red_team_banned_tids_linux) }}"
  when:
    - ansible_system == 'Linux'

- name: Run invoke-atomictest on each TID (windows)
  ansible.builtin.include_tasks: invoke-atomictest.yml
  loop: "{{ atomic_red_team_art_tids_windows | difference(atomic_red_team_banned_tids_windows) }}"
  when:
    - ansible_system == 'Win32NT'
